[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
airbnb_blockhain = "5FeA9qBzmvEDreexhEMmivcz9KccuhCZaqWWVYxtkgm9"

[programs.devnet]
airbnb_blockhain = "9fD3JVVmbzGC66pTYb5xZCXc24ibEYcM8vMrWoQjMfW5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.develop.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
