version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: airbnb-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: airbnb_clone
    volumes:
      - mongodb_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - airbnb-network

  # Optional: MongoDB Express for database management UI
  mongo-express:
    image: mongo-express:1.0.0
    container_name: airbnb-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - airbnb-network

volumes:
  mongodb_data:
    driver: local

networks:
  airbnb-network:
    driver: bridge
